### ISSUE TITLE
Cannot search BUNNY coin

### ISSUE THREAD

**Issue by chrisleekr** [d0x2f/Gnome-CrytoKit#1]
I can search BUNNY in coincap.io - https://coincap.io/assets/pancakebunny
But I cannot search in the portfolio asset.

BUNNY is not supported?

**Comment by d0x2f** [comment]
Ah you're right I hadn't noticed but the assets endpoint is limited to 100 results by default.
I can bump that up to 2000.

https://docs.coincap.io/

**Comment by d0x2f** [comment]
Fixed and submitted to extensions.gnome.org
